### PR TITLE
80218 Show dates as UTC times

### PR DESCRIPTION
**Pull request by bratli**
DevOps#80218

Show datetimes with Z at the end to indicate UTC times

### CODE REVIEW

**Comment by janid1967** [comment]
Why not add either .HasConversion(PreservationContext.DateTimeKindConverter); or .HasConversion(PreservationContext.NullableDateTimeKindConverter); for all DateTime props in all entities?
Sample: Participant.SignedAtUtc

**Review by janid1967 — CHANGES_REQUESTED** [review]
Why not add either .HasConversion(PreservationContext.DateTimeKindConverter); or .HasConversion(PreservationContext.NullableDateTimeKindConverter); for all DateTime props in all entities?
Sample: Participant.SignedAtUtc

**Comment by bratli** [comment]
> Why not add either .HasConversion(PreservationContext.DateTimeKindConverter); or .HasConversion(PreservationContext.NullableDateTimeKindConverter); for all DateTime props in all entities?
> Sample: Participant.SignedAtUtc
@janid1967 
Do you mean that there are other DateTime-props where I should add this? Participant.SignedAtUtc is a part of this PR, but maybe it should be NullableDateTimeKindConverter instead of DateTimeKindConverter, since we can set it to null?

**Comment by janid1967** [comment]
> > Why not add either .HasConversion(PreservationContext.DateTimeKindConverter); or .HasConversion(PreservationContext.NullableDateTimeKindConverter); for all DateTime props in all entities?
> > Sample: Participant.SignedAtUtc
> > @janid1967
> > Do you mean that there are other DateTime-props where I should add this? Participant.SignedAtUtc is a part of this PR, but maybe it should be NullableDateTimeKindConverter instead of DateTimeKindConverter, since we can set it to null?

I missed that Participant.SignedAtUtc was in the PR. You're correct: Use NullableDateTimeKindConverter

**Review by janid1967 — APPROVED** [review]

**Pull request merged**
