### PR TITLE
Using TimeService NuGet package.

### PR DESCRIPTION
**Pull request by hbjorgo**
Replaced TimeService with NuGet package.
What do you think?

### CODE REVIEW

**Comment by paal123** [comment]
I dont quite see the value of adding an external nuget package for this.

In addition I like  that we explicity use UtcNow, it makes i much easier to read and avoid confusion.

**Comment by janid1967** [comment]
> In addition I like that we explicity use UtcNow, it makes i much easier to read and avoid confusion.

Kanskje HeboTech kan endre til UtcNow? :)

**Comment by hbjorgo** [comment]
All projects will use the same code and we don't need to copy code between projects.
Using a Func instead of interfaces/the current implementation removes the need to create stubs when testing.

Renaming to UtcNow will make the code more cluttered, because of all the UTC checks, and setting the time during testing is more elaborate (using UTC during testing is usually not necessary).
Adding UtcNow will make it possible to use both Now and UtcNow in the code, which can lead to bad behavior.
By only exposing Now, there is no other choice in the code. During application initialization, the provider is set to return UtcNow.

Just a proposal to reduce duplication and clutter :)

**Review by janid1967 — APPROVED** [review]
Fine for me, but then HeboTech must do the same in Pres API too ;-)

**Comment by paal123** [comment]
I would not recommend including an external library with ~100 downloads. Then we should rather write our own owned by Equinor to have controll of security and fixes. I dont see any value in adding small "unverified" libraries to our solutions from a security perspective.

**Review by paal123 — CHANGES_REQUESTED** [review]
Not recommended

**Comment by paal123** [comment]
Not in accordance with Equinor policy

**Pull request closed without merging**
